# Generated by Django 3.0.8 on 2020-07-17 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('author_email', models.CharField(max_length=100, verbose_name='Email')),
                ('comment_texr', models.TextField(verbose_name='Text of comment')),
            ],
        ),
    ]
